In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [15]:
X, y = make_classification(n_samples=5000, n_features=15, n_classes=3, n_clusters_per_class=1)
X_test = X[4000:]
y_test = y[4000:]
X_train = X[:4000]
y_train = y[:4000]

In [34]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_probs = gnb.predict_proba(X_test)
print('The prior classes are\n', gnb.class_prior_)
print('\nThe predicted probabilities are\n', y_pred_probs)

The prior classes are
 [ 0.33475  0.33225  0.333  ]

The predicted probabilities are
 [[  2.79757978e-07   9.59260323e-02   9.04073688e-01]
 [  3.46608042e-05   2.12322292e-01   7.87643047e-01]
 [  2.19032705e-04   9.48634841e-01   5.11461264e-02]
 ..., 
 [  5.74027254e-07   9.99735093e-01   2.64333026e-04]
 [  9.99997939e-01   8.25858964e-25   2.06062857e-06]
 [  2.28092160e-07   3.46222188e-01   6.53777584e-01]]
