In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Basic Concepts:
* Average
* standard deviation
* $d$-dimensional vectors.
* Mean of vectors
* STD of vectors

In [6]:
a=np.random?

In [12]:
a=np.random.rand(3,5)
a

array([[ 0.88430467,  0.51887377,  0.10335021,  0.79528434,  0.36768694],
       [ 0.02308904,  0.39520012,  0.63105549,  0.3224381 ,  0.56286244],
       [ 0.80426479,  0.95278724,  0.24740148,  0.75246899,  0.65549071]])

In [16]:
mean(a,axis=0)

array([ 0.57055284,  0.62228704,  0.32726906,  0.62339714,  0.52868003])

In [17]:
std(a,axis=0)

array([ 0.388492  ,  0.23909075,  0.22271407,  0.21352681,  0.11995577])